version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3206:5000"
    volumes:
      - ../build:/build
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
